version: '3.5'
services:
  mysql_wp: 
    image: mysql:5.7
    container_name: mysql_wp_docker
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ./docker/database:/var/lib/mysql
  nginx_wp:
    image: nginx:latest
    container_name: nginx_wp_docker
    restart: always
    ports:
      - "8080:80"
      - "4430:443"
    volumes: 
      - ./docker/sites/:/etc/nginx/conf.d/
      - type: bind
        source: .
        target: /project
    working_dir: /project
    dns: 
      - 192.168.2.6
      - 8.8.8.8
  fpm:
    build: ./docker/dockerBuild
    image: php:fpm-composer
    container_name: php_fpm_wp_docker
    restart: always
    ports: 
      - "9000:80"
    volumes: 
      - type: bind
        source: .
        target: /project
    working_dir: /project
