version: '3.5'
services:
  mysql_wp: 
    image: mysql:5.7
    container_name: ${DOCKER_MYSQL_CONTAINER_NAME}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DOCKER_MYSQL_EXPOSE_PORT}:${DOCKER_MYSQL_INTERNAL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ./docker/database:/var/lib/mysql
  nginx_wp:
    image: nginx:latest
    container_name: ${DOCKER_NGINX_CONTAINER_NAME}
    restart: always
    ports:
      - "${DOCKER_NGINX_EXPOSE_PORT}:${DOCKER_NGINX_INTERNAL_PORT}"
      - "443:443"
    volumes: 
      - ./docker/sites/:/etc/nginx/conf.d
      - ./docker/logs/:/var/log/nginx
      - .:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}
  fpm_wp:
    build: ./docker/dockerBuild
    image: php:fpm-composer
    container_name: ${DOCKER_FPM_CONTAINER_NAME}
    restart: always
    ports: 
      - "${DOCKER_FPM_EXPOSE_PORT}:${DOCKER_FPM_INTERNAL_PORT}"
    volumes: 
      - .:${PROJECT_DIR}
      - ./../../shared:/shared/
    working_dir: ${PROJECT_DIR}
