stevehardware.me:
  stage: test
  user: stevele
  port: 22
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  deploy_path: /srv/deployer-source/{{application}}
  extra_param: "foo {{hostname}}"