FROM php:fpm
RUN export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
        && apt-get update && apt-get install -y \
        libcurl4-gnutls-dev\
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libxml2-dev \
        libmagickwand-dev \
        libzip-dev \
        nano \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) mysqli pdo_mysql intl gd zip exif\
    && rm -rf /var/lib/apt/lists/* \
    && pecl install imagick-3.4.3 && docker-php-ext-enable imagick \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug
# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer